language: go
go:
  - '1.14'

before_install:
  - go get github.com/mattn/goveralls

script:
  - ls && make build && ls
  - goveralls -service=travis-ci

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GitHub_Token  # Your GitHub token set in Travis CI console
  target_branch: master        # Add this line - To push into GitHub master branch
  on:
    branch: master            # Your GitHub repo default branch
