version: "3.6"
services:
  blogapi:
    restart: always
    build:
      context: ./
      dockerfile: dockerfile
    image: blogapi
    container_name: blogapi
    ports:
      - 8080:8080
    volumes:
      - ./logs/api:/blog/log

    mysql:
      network_mode: "bridge"
      environment:
        MYSQL_ROOT_PASSWORD: "yourpassword"
        MYSQL_USER: 'test'
        MYSQL_PASS: 'yourpassword'
      image: "mysql"
      restart: always
      volumes:
        - "./db:/var/lib/mysql"
      ports:
        - "3306:3306"