version: "3.6"
services:
  blogapi:
    restart: always
    build:
      context: ./
      dockerfile: dockerfile
    image: blogapi
    container_name: blogapi
    ports:
      - 8080:8080
    volumes:
      - ./logs/api:/blog/log