version: "3.6"
services:
  blogapi:
    restart: always
    build:
      context: ./
      dockerfile: dockerfile
    image: blogapi
    container_name: blogapi
    ports:
      - 82:8080
    volumes:
      - ./logs/api:/blog/log

  mysql:
    network_mode: "bridge"
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "yourpassword"
      MYSQL_USER: 'test'
      MYSQL_PASS: 'yourpassword'
    image: "mysql"
    restart: always
    volumes:
      - "./db:/var/lib/mysql"
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 8100:8100
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./data:/data:rw
    command:
      /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf "